# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('building_number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
